Repository SupRemaZie/LODGER, pull requests merged in 2025-04, with the labels that each got.

#46 43 ajouter la logique aux entrées formulaires
  app/[locale]/deposit/page.tsx
  app/ui/components/FormEntry.tsx
  public/icons/bed-icon.svg
  public/icons/matter-icon.svg
  public/icons/shower-icon.svg
  public/icons/sofa-icon.svg
Labels: enhancement, UX

#48 17 créer un composant bouton
  app/[locale]/deposit/page.tsx
  app/ui/components/LodgerButton.tsx
  public/icons/flag_en.svg
  public/icons/flag_fr.svg
Labels: enhancement, UX

#61 feat : create view step one
  app/[locale]/deposit/layout.tsx
  app/[locale]/deposit/page.tsx
  app/ui/components/sidenav.tsx
  messages/en.json
  messages/fr.json
  public/customers/amy-burns.png
  public/customers/balazs-orban.png
  public/customers/delba-de-oliveira.png
  public/customers/evil-rabbit.png
  public/customers/lee-robinson.png
  public/customers/michael-novotny.png
  public/hero-desktop.png
  public/hero-mobile.png
  public/images/appartment_choice_picture.png
  public/images/house_choice_picture.png
  public/images/line-empty.svg
  public/images/line-full.svg
  public/images/logo_lodger.png
  public/opengraph-image.png
  tests/test.spec.ts
Labels: UX

#63 fix : correction bug images button
  app/[locale]/deposit/page.tsx
  tests/test.spec.ts
Labels: bug

#101 Version BETA 0.8
  app/[locale]/deposit/apartment/page.tsx
  app/[locale]/deposit/dpe/page.tsx
  app/[locale]/deposit/features/page.tsx
  app/[locale]/deposit/home/page.tsx
  app/[locale]/deposit/information/page.tsx
  app/[locale]/deposit/localisation/page.tsx
  app/[locale]/deposit/page.tsx
  app/[locale]/layout.tsx
  app/[locale]/page.tsx
  app/[locale]/test/layout.tsx
  app/[locale]/test/page.tsx
  app/api/deposit/deposit.ts
  app/api/interface.ts
  app/context/FormDataContext.tsx
  app/tools/AddressFormatter.tsx
  app/ui/components/AddressMap.tsx
  app/ui/components/DPE_components.tsx
  app/ui/components/Footer.tsx
  app/ui/components/FormEntry.tsx
  app/ui/components/Header.tsx
  app/ui/components/sidenav.tsx
  app/ui/components/test.tsx
  messages/en.json
  messages/fr.json
  package.json
Labels: enhancement

#111 update gitignore, remove .vscode settings folder
  .gitignore
  .vscode/settings.json
Labels: bug, BACK

#113 Correction du bug
  app/ui/components/sidenav.tsx
Labels: bug, UX
